version: "3"

services:
  flask:
    build:
      context: .
    ports:
      - "8004:8004"
    volumes:
      - .:/code
    environment:
      - VIRTUAL_HOST=emojionz.shirleyyin.com
    restart: always

networks:
  default:
    external:
      name: nginxproxy_default
